version: "3.9"

services:
  mariadb:
    environment:
      MARIADB_DATABASE: foobar
      MARIADB_PASSWORD: foobar
      MARIADB_ROOT_PASSWORD: foobar
      MARIADB_USER: foobar
      TZ: UTC
    image: mariadb:10.11
    ports:
      - "13306:3306"
    restart: unless-stopped
    volumes:
      - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
